server:
  port: 8088

jwt:
  signerKey: "qUIO01I4tQtECy3nFMP4kI1RK27VqetVfCMf+SQJpnL+xVN9Cv1w7HCkvEPsGTVW"
  token-valid-duration: 86400  #seconds
  token-refreshable-duration: 864000  #seconds 10 days

json-encrypt-password: "qUIO01I4tQtECy3nFMP4kI1RK27VqetVfCMf+SQJpnL+xVN9Cv1w7HCkvEPsGTVW"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/webchiasetailieu"
    username: root
    password: vuhoangquan2004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  mail:
    host: smtp.gmail.com         # địa chỉ máy chủ SMTP của bạn
    port: 587                       # cổng SMTP, thường là 587 cho TLS hoặc 465 cho SSL
    username: pdfhubsharedoc@gmail.com
    password: oiul bfxo kugn rmcf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
